import setuptools

scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setuptools.setup(
    name="ts_atspectrograph",
    description="CSC for the Auxiliary Telescope Spectrograph. ",
    use_scm_version={
        "write_to": "python/lsst/ts/atspectrograph/version.py",
        "write_to_template": scm_version_template,
    },
    setup_requires=["setuptools_scm"],
    extras_require={"dev": ["documenteer[pipelines]"]},
    package_dir={"": "python"},
    packages=setuptools.find_namespace_packages(where="python"),
    package_data={"": ["*.rst", "*.yaml"]},
    scripts=["bin/atspec_csc.py"],
    license="GPL",
    project_urls={
        "Bug Tracker": "https://jira.lsstcorp.org/secure/Dashboard.jspa",
        "Source Code": "https://github.com/lsst-ts/ts_atspec",
    },
)
