{% set data= load_setup_py_data() %}
package:
  name: "ts-atspec"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  noarch: python
  entry_points:
    - run_atspectrograph_csc = lsst.ts.atspectrograph.atspec_csc:run_atspectrograph_csc

test:
  requires:
    - ts-conda-build =0.5
    - ts-xml {{ xml_version }}
    - ts-salobj {{ salobj_version }}
  source_files:
    - python
    - bin
    - tests
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm ={{setuptools_scm}}
    - setuptools >={{setuptools}}
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-salobj
    - ts-xml
