settingVersions:
  recommendedSettingsVersion: 'default'
  recommendedSettingsLabels: ['default', 'simulation']

setting:
  default:
    host: '140.252.32.156'  # IP of the weather station
    port: 9999
    filters:
      - "u"
      - "g"
      - "r"
      - "i"
      - "z"
    gratings:
      - "red"
      - "blue"
    linear_stage:
      min_pos: 0
      max_pos: 1000
      speed: 10
